import { memo, useState, useEffect } from 'react';
import 'katex/dist/katex.min.css';

interface Props {
    latex: string;
    className?: string;
    displayMode?: boolean;
    /** Friendly text equivalent for assistive tech (e.g. "9 divided by 3").
     *  When omitted, the raw KaTeX MathML annotation may be announced verbatim. */
    ariaLabel?: string;
}

/**
 * Renders a LaTeX string using KaTeX (lazy-loaded).
 * Shows raw LaTeX as fallback while KaTeX loads.
 *
 * KaTeX output is sanitized at the source (`renderToString` escapes content
 * and the `latex` argument is never user-controlled — it's generated by
 * mathGenerator/dailyChallenge), so the `dangerouslySetInnerHTML` here is
 * scoped to trusted input only.
 *
 * Accessibility: when `ariaLabel` is supplied we expose a friendly label and
 * hide the KaTeX subtree from AT — otherwise screen readers may read the raw
 * `\div` source from the MathML annotation.
 */
export const MathExpr = memo(function MathExpr({ latex, className = '', displayMode = false, ariaLabel }: Props) {
    const [html, setHtml] = useState<string | null>(null);

    useEffect(() => {
        let cancelled = false;
        import('katex').then(({ default: katex }) => {
            if (cancelled) return;
            try {
                setHtml(katex.renderToString(latex, { throwOnError: false, displayMode }));
            } catch {
                setHtml(latex);
            }
        });
        return () => { cancelled = true; };
    }, [latex, displayMode]);

    if (html === null) {
        return (
            <span className={className} aria-label={ariaLabel}>
                {ariaLabel ? <span aria-hidden="true">{latex}</span> : latex}
            </span>
        );
    }

    return (
        <span
            className={className}
            aria-label={ariaLabel}
            role={ariaLabel ? 'img' : undefined}
        >
            <span
                aria-hidden={ariaLabel ? true : undefined}
                dangerouslySetInnerHTML={{ __html: html }}
            />
        </span>
    );
});
